#include "station_lockup.h"

static const Station stations[] = {
    {"Arnn", "Arlanda"},
    {"Ab", "Arbrå"},
    {"Apn", "Aspen"},
    {"Avky", "Avesta Krylbo"},
    {"Bdf", "Bodafors"},
    {"Bdy", "Bredaryd"},
    {"Bfo", "Billingsfors"},
    {"Bg", "Berga"},
    {"Bkb", "Barkarby"},
    {"Bl", "Ballingslöv"},
    {"Blgc", "Borlänge C"},
    {"Blv", "Burlöv"},
    {"Bml", "Bromölla"},
    {"Bn", "Bollnäs"},
    {"Boa", "Borgstena"},
    {"Bro", "Bro"},
    {"Bsc", "Borås C"},
    {"Cg", "Charlottenberg"},
    {"Dis", "Diö"},
    {"Dre", "Derome"},
    {"Dtc", "Dorotea camping"},
    {"Ei", "Erikslund"},
    {"Em", "Emmaboda"},
    {"En", "Edane"},
    {"F", "Falköping C"},
    {"Fc", "Framnäs city"},
    {"Fjå", "Fjällåsen"},
    {"Fki", "Fjälkinge"},
    {"Fkr", "Fåker"},
    {"Flb", "Flemingsberg"},
    {"Fm", "Forserum"},
    {"Frå", "Frykåsen"},
    {"Fs", "Fors"},
    {"Ft", "Fränsta"},
    {"Fud", "Furulund"},
    {"G", "Göteborg C"},
    {"Gdö", "Gårdsjö"},
    {"Gm", "Gemla"},
    {"Gn", "Gnesta"},
    {"Gnb", "Gunnesbo"},
    {"Gss", "Gärsnäs"},
    {"Gä", "Gävle C"},
    {"Gö", "Gällö"},
    {"Hb", "Helsingborg C"},
    {"Hbd", "Högboda"},
    {"Hdm", "Hedemora"},
    {"Het", "Hestra"},
    {"Hf", "Hultsfred"},
    {"Hgv", "Häggvik"},
    {"Hls", "Hällnäs"},
    {"Hnä", "Hälleforsnäs"},
    {"Hsr", "Hasslerör"},
    {"Hvp", "Hovmantorp"},
    {"Hy", "Heby"},
    {"Häp", "Häljarp"},
    {"Hö", "Höör"},
    {"Höy", "Högsby"},
    {"Id", "Iggesund"},
    {"Jbo", "Jordbro"},
    {"Jk", "Jokkmokk"},
    {"Jn", "Järna"},
    {"Jps", "Järpås"},
    {"Js", "Jämtlands Sikås"},
    {"Kbn", "Karbenning"},
    {"Kda", "Krigslida"},
    {"Kde", "Kode"},
    {"Kil", "Kil"},
    {"Kjå", "Katterjåkk"},
    {"Kls", "Kilafors"},
    {"Kms", "Kimstad"},
    {"Kn", "Knivsta"},
    {"Kns", "Kolsnäs"},
    {"Krm", "Krokom"},
    {"Kvi", "Kvidinge"},
    {"Kän", "Kungsängen"},
    {"La", "Ludvika"},
    {"Laov", "Laholm"},
    {"Lb", "Lingbo"},
    {"Lgm", "Linghem"},
    {"Lhr", "Lillhamra"},
    {"Lis", "Liseberg"},
    {"Lit", "Lit"},
    {"Lju", "Ljung"},
    {"Ljv", "Ljungaverk"},
    {"Lkö", "Landskrona"},
    {"Lme", "Limmared"},
    {"Lse", "Ljusne"},
    {"Ly", "Lycksele"},
    {"Lyv", "Lysvik"},
    {"Lå", "Laxå"},
    {"Meh", "Mehedeby"},
    {"Mia", "Maria"},
    {"Mkl", "Munkedal"},
    {"Mlf", "Meselefors"},
    {"Moy", "Mollaryd"},
    {"Mpb", "Persborg"},
    {"Mru", "Mörrum"},
    {"Mu", "Mullsjö"},
    {"Nd", "Nässundet"},
    {"Ngd", "Nynäsgård"},
    {"Nhr", "Norrahammar"},
    {"Njb", "Njurundabommen"},
    {"Nk", "Nyköping C"},
    {"Nkv", "Nykvarn"},
    {"Nol", "Nol"},
    {"Nr", "Norrköping C"},
    {"Ns", "Norsesund"},
    {"Nvk", "Norrviken"},
    {"Nyb", "Nybro"},
    {"No.nk", "Narvik"},
    {"Ol", "Oleby"},
    {"Ot", "Ottebol"},
    {"Ox", "Oxie"},
    {"P", "Partille"},
    {"Pt", "Perstorp"},
    {"Rdg", "Rydsgård"},
    {"Rf", "Rimforsa"},
    {"Rft", "Reftele"},
    {"Rs", "Rosersberg"},
    {"Rt", "Ransta"},
    {"Rts", "Rottneros"},
    {"Rv", "Rättvik"},
    {"Ryä", "Rydebäck"},
    {"Röp", "Rörstorp"},
    {"S", "Sveg"},
    {"Sae", "Sandared"},
    {"Sal", "Svalöv"},
    {"Sarp", "Sannarp"},
    {"Sdnä", "Sandsjönäs"},
    {"Sdy", "Smedby"},
    {"Sea", "Svedala"},
    {"Sgä", "Slagnäs"},
    {"Shv", "Söderhamn"},
    {"Si", "Simrishamn"},
    {"Skb", "Skinnskatteberg"},
    {"Ske", "Skee"},
    {"Sm", "Sandhem"},
    {"Smj", "Smedjebacken"},
    {"Snu", "Stenungsund"},
    {"So", "Solna"},
    {"Sol", "Sollentuna"},
    {"Spå", "Spånga"},
    {"Srn", "Sörtjärn"},
    {"Ss", "Stenstorp"},
    {"Std", "Stöde"},
    {"Sth", "Stora Höga"},
    {"Stlv", "Stora Levene"},
    {"Stp", "Svågertorp"},
    {"Str", "Storlien"},
    {"Sue", "Surte"},
    {"Sus", "Sunderby sjukhus"},
    {"Syd", "Skillingaryd"},
    {"Söd", "Södertälje hamn"},
    {"Söla", "Sösdala"},
    {"Tgp", "Tågarp"},
    {"Th", "Tenhult"},
    {"Tip", "Tierp"},
    {"Tjsk", "Tjustskolan"},
    {"Tli", "Tomelilla"},
    {"Tns", "Tranås"},
    {"Tof", "Tofta"},
    {"Tre", "Trekanten"},
    {"Trm", "Trolmen"},
    {"Trå", "Timrå"},
    {"Tså", "Torsåker"},
    {"Tu", "Tumba"},
    {"Tåd", "Trångsund"},
    {"Tö", "Tjörnarp"},
    {"Uv", "Uddevalla C"},
    {"Vag", "Vargön"},
    {"Vaj", "Varjisträsk"},
    {"Vby", "Vännäsby"},
    {"Ved", "Vedum"},
    {"Vfa", "Vissefjärda"},
    {"Vhd", "Vagnhärad"},
    {"Vhe", "Västerhaninge"},
    {"Vl", "Vallsta"},
    {"Vs", "Vislanda"},
    {"Vsj", "Vittsjö"},
    {"Vso", "Virsbo"},
    {"Vta", "Vetlanda"},
    {"Våk", "Vallåkra"},
    {"Vöv", "Vinslöv"},
    {"Yb", "Ytterby"},
    {"Ånn", "Ånn"},
    {"Åp", "Åstorp"},
    {"Åsa", "Åsa"},
    {"Åsal", "Åsarna C"},
    {"Åvg", "Åtvidaberg"},
    {"Äh", "Älmhult"},
    {"Äkb", "Älvkarleby"},
    {"Öb", "Örebro S"},
    {"Öte", "Östertälje"},
    {"Övb", "Överby"},
    {"Öäg", "Österäng"},
    {"A", "Alingsås"},
    {"Acm", "Avesta C"},
    {"Ar", "Arvika"},
    {"Auk", "Auktsjaur"},
    {"Ava", "Avaviken"},
    {"Baa", "Barkåkra"},
    {"Bgm", "Berghem"},
    {"Bih", "Billesholm"},
    {"Bjuv", "Bjuv"},
    {"Bma", "Blomstermåla"},
    {"Bmb", "Blomberg"},
    {"Bnk", "Blattnicksele"},
    {"Bor", "Bor"},
    {"Boy", "Bollebygd"},
    {"Brin", "Brinellskolan"},
    {"Bth", "Basthagen"},
    {"Bur", "Buresjön"},
    {"Bål", "Bålsta"},
    {"Bä", "Bräcke"},
    {"Cst", "Stockholm C"},
    {"Dg", "Degerfors"},
    {"Dl", "Dingle"},
    {"Dt", "Dingtuna"},
    {"Du", "Duved"},
    {"Dös", "Dösjebro"},
    {"Ep", "Enköping"},
    {"Et", "Eskilstuna C"},
    {"Fal", "Falerum"},
    {"Fby", "Floby"},
    {"Fgå", "Fagerås"},
    {"Fiä", "Filsbäck"},
    {"Fle", "Flen"},
    {"Fln", "Falun C"},
    {"Fra", "Fristad"},
    {"Frl", "Fritsla"},
    {"För", "Förslöv"},
    {"Gal", "Gamleby"},
    {"Gan", "Gantofta"},
    {"Gdv", "Gröndalsviken"},
    {"Gg", "Grängesberg"},
    {"Ghy", "Grythyttan"},
    {"Gnf", "Gagnef"},
    {"Gnp", "Gnarp"},
    {"Gnö", "Gnosjö"},
    {"Gvc", "Gällivare C"},
    {"Hbgb", "Ramlösa"},
    {"Hd", "Halmstad C"},
    {"Hdn", "Holmsveden"},
    {"Hfr", "Hofors"},
    {"Hgs", "Häggenås"},
    {"Hh", "Hallstahammar"},
    {"Hjp", "Hjärup"},
    {"Hka", "Huskvarna"},
    {"Hkl", "Hudiksvall"},
    {"Hks", "Hackås"},
    {"Hlf", "Hällefors"},
    {"Hlr", "Horndals Bruk"},
    {"Hova", "Hova"},
    {"Hrc", "Herrljunga C"},
    {"Hre", "Horred"},
    {"Hsd", "Härnösand C"},
    {"Hum", "Husum"},
    {"Håp", "Håkantorp"},
    {"Höf", "Hörnefors"},
    {"Jkb", "Jakobsberg"},
    {"Jr", "Järvsö"},
    {"Jrn", "Jörn"},
    {"Jv", "Jonsered"},
    {"Jö", "Jönköping C"},
    {"Kb", "Kungsbacka"},
    {"Kbä", "Kolbäck"},
    {"Ke", "Karlberg"},
    {"Kg", "Kävlinge"},
    {"Kgå", "Klostergården"},
    {"Khe", "Hede"},
    {"Kid", "Kinnared"},
    {"Kin", "Kinna"},
    {"Kisa", "Kisa"},
    {"Kla", "Kumla"},
    {"Kll", "Källby"},
    {"Kmb", "Kiruna"},
    {"Kp", "Köping"},
    {"Kr", "Killeberg"},
    {"Ksus", "Kvicksund"},
    {"Ktm", "Kaitum"},
    {"Kvh", "Klevshult"},
    {"Köp", "Köpingebro"},
    {"Le", "Luleå"},
    {"Len", "Lene"},
    {"Les", "Lödöse Södra"},
    {"Lgb", "Långbron"},
    {"Lj", "Ljungskile"},
    {"Lnå", "Lugnås"},
    {"Lo", "Lessebo"},
    {"Lr", "Lerum"},
    {"Lrd", "Landeryd"},
    {"Ls", "Ljusdal"},
    {"Lu", "Lund C"},
    {"Lve", "Lovene"},
    {"Låk", "Låktatjåkka"},
    {"Löb", "Lövberga"},
    {"Maa", "Marma"},
    {"Mar", "Marieholm"},
    {"Mdn", "Mölndal"},
    {"Mfn", "Munkflohögen"},
    {"Mk", "Murjek"},
    {"Mo", "Moheda"},
    {"Myk", "Mölnlycke"},
    {"Mö", "Mölnbo"},
    {"N", "Nässjö C"},
    {"Nka", "Nykroppa"},
    {"Nä", "Nälden"},
    {"O", "Osby"},
    {"Ob", "Ockelbo"},
    {"Om", "Oskarström"},
    {"Pl", "Pilgrimstad"},
    {"R", "Rotebro"},
    {"Rb", "Ronneby"},
    {"Rgn", "Riksgränsen"},
    {"Rjn", "Röjan"},
    {"Rkö", "Rocksjön"},
    {"Sci", "Stockholm City"},
    {"Sgs", "Strängnäs"},
    {"Skg", "Skogås"},
    {"Skn", "Skänninge"},
    {"Sl", "Sala"},
    {"Sn", "Stenkullen"},
    {"Snv", "Sandviken"},
    {"Sr", "Storå"},
    {"Sre", "Söderbärke"},
    {"Ssä", "Segersäng"},
    {"Ste", "Svarte"},
    {"Sum", "Storuman"},
    {"Sur", "Skutskär"},
    {"Svc", "Svenstavik C"},
    {"Säv", "Sävenäs"},
    {"Söc", "Södertälje C"},
    {"Sög", "Sölvesborg"},
    {"Söu", "Södertälje Syd (SL)"},
    {"T", "Töreboda"},
    {"Tag", "Taberg"},
    {"Tbo", "Tobo"},
    {"Tby", "Tandsbyn"},
    {"Thn", "Trollhättan"},
    {"Tn", "Tannefors"},
    {"To", "Torpshammar"},
    {"Top", "Torpåkra"},
    {"Tri", "Triangeln"},
    {"Ty", "Tyringe"},
    {"Un", "Undersåker"},
    {"Upv", "Upplands Väsby"},
    {"Uåö", "Umeå Ö"},
    {"V", "Värnamo"},
    {"Vdn", "Vindeln"},
    {"Vfo", "Viskafors"},
    {"Vga", "Vega"},
    {"Vha", "Vattholma"},
    {"Vib", "Vimmerby"},
    {"Vid", "Västra Ingelstad"},
    {"Vj", "Vassijaure"},
    {"Vsd", "Vikingstad"},
    {"Vtn", "Vattnäs"},
    {"Vå", "Västerås C"},
    {"Vät", "Västra Ämtervik"},
    {"Yl", "Ytterhogdal"},
    {"Åb", "Åsensbruk"},
    {"Åbe", "Årstaberg"},
    {"Åg", "Ånge"},
    {"Åk", "Åkarp"},
    {"Ål", "Åmål"},
    {"Åt", "Åmotfors"},
    {"Än", "Älvängen"},
    {"Äsr", "Äskekärr"},
    {"Ög", "Östra Grevie"},
    {"Öh", "Örbyhus"},
    {"Öhl", "Överhogdal"},
    {"Ök", "Örnsköldsvik C"},
    {"Ökn", "Örnsköldsvik N"},
    {"Önd", "Önnestad"},
    {"Ör", "Örebro C"},
    {"Örs", "Örsjö"},
    {"Öso", "Ösmo"},
    {"Ösv", "Östersund V"},
    {"Öx", "Öxnered"},
    {"Ag", "Anneberg"},
    {"Ajr", "Arvidsjaur"},
    {"Ak", "Abisko Östra"},
    {"Akt", "Abisko turiststation"},
    {"Alv", "Astrid Lindgrens värld"},
    {"Any", "Aneby"},
    {"Arb", "Arboga"},
    {"Arnc", "Arlanda C"},
    {"Asb", "Assberg"},
    {"Asd", "Aspedalen"},
    {"Av", "Alvesta"},
    {"Bdn", "Boden C"},
    {"Bf", "Brunflo"},
    {"Bhb", "Bräkne-Hoby"},
    {"Bhs", "Bohus"},
    {"Bib", "Billeberga"},
    {"Bjm", "Bjärnum"},
    {"Bjo", "Björketorp"},
    {"Bjy", "Björköby"},
    {"Bln", "Björkliden"},
    {"Bry", "Bankeryd"},
    {"Brö", "Bredsjö"},
    {"Bst", "Bastuträsk"},
    {"But", "Buterud"},
    {"Bx", "Boxholm"},
    {"Båa", "Bergåsa"},
    {"Bån", "Båstad"},
    {"Bäb", "Bäckebron"},
    {"Ck", "Karlskrona C"},
    {"Cr", "Kristianstad C"},
    {"Då", "Djurås"},
    {"E", "Eslöv"},
    {"Ebk", "Edsbjörke"},
    {"Ed", "Ed"},
    {"Ek", "Eksjö"},
    {"Ens", "Enafors"},
    {"Esn", "Ekenässjön"},
    {"Fabp", "Falkenberg"},
    {"Fas", "Farsta strand"},
    {"Fd", "Floda"},
    {"Feö", "Fågelsjö"},
    {"Fgc", "Fagersta C"},
    {"Fgn", "Fagersta Norra"},
    {"Fhm", "Forshem"},
    {"Flgd", "Friluftsgården"},
    {"Fod", "Forsheda"},
    {"Fv", "Frövi"},
    {"Fvk", "Furuvik"},
    {"Gas", "Gamlestaden"},
    {"Glv", "Glumslöv"},
    {"Gms", "Grums"},
    {"Gop", "Grästorp"},
    {"Gpc", "Geogr. Polcirkeln"},
    {"Hel", "Helenelund"},
    {"Hfa", "Hemfosa"},
    {"Hie", "Hyllie"},
    {"Hlk", "Hällekis"},
    {"Hlv", "Hällevadsholm"},
    {"Hm", "Hässleholm"},
    {"Hmö", "Holmsjö"},
    {"Hnd", "Handen"},
    {"Ho", "Habo"},
    {"Hok", "Hok"},
    {"Hp", "Haparanda"},
    {"Hpbg", "Hallsberg"},
    {"Htg", "Hoting"},
    {"Hu", "Huddinge"},
    {"Hv", "Hästveda"},
    {"Hvr", "Håverud"},
    {"Hvs", "Hovslätt"},
    {"Hås", "Hindås"},
    {"In", "Insjön"},
    {"Jli", "Jamtli"},
    {"Jpn", "Järpen"},
    {"K", "Katrineholm C"},
    {"Ka", "Kattarp"},
    {"Kac", "Kalmar C"},
    {"Kd", "Kågeröd"},
    {"Kh", "Karlshamn"},
    {"Khn", "Kristinehamn"},
    {"Khä", "Kallhäll"},
    {"Kl", "Klippan"},
    {"Klxv", "Kalix Västra"},
    {"Knl", "Knalleland"},
    {"Kon", "Kolmården"},
    {"Kpg", "Kopparberg"},
    {"Krd", "Kållered"},
    {"Krf", "Kramfors"},
    {"Ksc", "Karlstad C"},
    {"Kvä", "Välsviken"},
    {"Kvö", "Kvarnsjö"},
    {"Kåb", "Kåbdalis"},
    {"Kör", "Kungsör"},
    {"Ld", "Lindesberg"},
    {"Ldo", "Lindome"},
    {"Lg", "Läggesta"},
    {"Lh", "Lammhult"},
    {"Lkp", "Lidköping"},
    {"Lma", "Lomma"},
    {"Lp", "Linköping C"},
    {"Lsd", "Leksand"},
    {"Lup", "Lunnarp"},
    {"Lyd", "Lyrestad"},
    {"M", "Malmö C"},
    {"Mbä", "Malmbäck"},
    {"Mi", "Mörsil"},
    {"Ml", "Mellerud"},
    {"Mos", "Moskosel"},
    {"Mot", "Motala C"},
    {"Mr", "Märsta"},
    {"Mras", "Morastrand"},
    {"Mrc", "Mora C"},
    {"Mrd", "Markaryd"},
    {"Mrl", "Mora lasarett"},
    {"Mst", "Mariestad"},
    {"Mt", "Mantorp"},
    {"My", "Mjölby"},
    {"Må", "Morgongåva"},
    {"Måp", "Månsarp"},
    {"Mör", "Mörarp"},
    {"Nog", "Nordmaling"},
    {"Ntv", "Nattavaara"},
    {"Nvn", "Notviken"},
    {"Nyc", "Nynäshamn"},
    {"Nöe", "Nödinge"},
    {"Ors", "Orsa"},
    {"Ory", "Ormaryd"},
    {"Pj", "Porjus"},
    {"Påa", "Påarp"},
    {"Rbh", "Rabbalshede"},
    {"Rbk", "Råbäck"},
    {"Rd", "Rävlanda"},
    {"Rmn", "Ramnäs"},
    {"Rog", "Rosengård"},
    {"Rym", "Rydaholm"},
    {"Rön", "Rönninge"},
    {"Sdr", "Smålandsstenar"},
    {"See", "Skene"},
    {"Sf", "Storfors"},
    {"Sfl", "Säffle"},
    {"Sg", "Stehag"},
    {"Shr", "Surahammar"},
    {"Sif", "Sikfors"},
    {"Sjka", "Sjisjka"},
    {"Sk", "Skövde C"},
    {"Skru", "Skållerud"},
    {"Smd", "Strömstad"},
    {"Smp", "Smedstorp"},
    {"Snö", "Stensjön"},
    {"Sod", "Stockholm Odenplan"},
    {"Srp", "Skurup"},
    {"Srs", "Sorsele"},
    {"Srv", "Storvreta"},
    {"Sst", "Stockholms S"},
    {"St", "Säter"},
    {"Sta", "Stuvsta"},
    {"Stb", "Stångby"},
    {"Stje", "Stjerneskolan"},
    {"Stl", "Ställdalen"},
    {"Stv", "Stavre"},
    {"Sub", "Sundbyberg"},
    {"Suc", "Sundsvall C"},
    {"Sun", "Sunne"},
    {"Suv", "Sundsvall V"},
    {"Sv", "Storvik"},
    {"Svg", "Svenshögen"},
    {"Sy", "Stockaryd"},
    {"Syt", "Skyttorp"},
    {"Sä", "Sävsjö"},
    {"Söö", "Södertälje Syd"},
    {"Tlg", "Tällberg"},
    {"Tlt", "Tolita"},
    {"Tnu", "Tanum"},
    {"Tou", "Torup"},
    {"Toy", "Torsby"},
    {"Tp", "Teckomatorp"},
    {"Trg", "Trelleborg"},
    {"Ts", "Tungelsta"},
    {"Tsl", "Tisselskog"},
    {"Tul", "Tullinge"},
    {"Tvd", "Torved"},
    {"Tvä", "Tvärålund"},
    {"U", "Uppsala C"},
    {"Udl", "Ulriksdal"},
    {"Uf", "Ulriksfors"},
    {"Uå", "Umeå C"},
    {"Uö", "Uddevalla Ö"},
    {"Vaa", "Vara"},
    {"Vad", "Vad"},
    {"Vb", "Varberg"},
    {"Vbd", "Västra Bodarne"},
    {"Vdi", "Veddige"},
    {"Ve", "Väse"},
    {"Vg", "Vänersborg C"},
    {"Vgd", "Vaggeryd"},
    {"Vgå", "Vårgårda"},
    {"Vjm", "Vojmån"},
    {"Vk", "Västervik"},
    {"Vma", "Vilhelmina"},
    {"Vman", "Vilhelmina norra"},
    {"Vns", "Vännäs"},
    {"Vr", "Vingåker"},
    {"Väy", "Västeraspby"},
    {"Vö", "Växjö"},
    {"Y", "Ystad"},
    {"Åre", "Åre"},
    {"Åsra", "Åsarna S"},
    {"Ä", "Ängelholm"},
    {"Äbg", "Ängelsberg"},
    {"Älo", "Älvho"},
    {"Äs", "Älvsjö"},
    {"Äy", "Älvsbyn"},
    {"Ö", "Örtofta"},
    {"Öda", "Ödåkra"},
    {"Öjr", "Öjervik"},
    {"Ös", "Östersund C"},
    {"Övmb", "Överums Bruk"},
    {"Övn", "Östervärn"}};

const size_t StationLookup::numStations = sizeof(stations) / sizeof(Station);

StationLookup &StationLookup::getInstance()
{
    static StationLookup instance; // Guaranteed to be destroyed, instantiated on first use.
    return instance;
}

String StationLookup::getStationName(const String &code)
{
    for (size_t i = 0; i < numStations; i++)
    {
        if (stations[i].code == code)
        {
            return stations[i].name;
        }
    }
    return code;
}

Station StationLookup::getStation(size_t index)
{
    if (index >= numStations)
    {
        return {"", ""};
    }
    return stations[index];
}

StationLookup::StationLookup() {}