name: Build PlatformIO Project

on:
  push:
    branches:
      - main
      - "feature/**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.0.0
        with:
          versionSpec: "6.x"

      - name: Determine Version
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v3.0.0

      - name: Generate constants header for OTA
        run: |
          echo "#ifndef OTA_CONSTANTS_H" > lib/ota_manager/src/ota_constants.h
          echo "#define OTA_CONSTANTS_H" >> lib/ota_manager/src/ota_constants.h
          echo "#include <Arduino.h>" >> lib/ota_manager/src/ota_constants.h
          echo "" >> lib/ota_manager/src/ota_constants.h
          echo "const String OTA_FIRMWARE_INFO_URL = \"${{ secrets.FIRMWARE_INFO_URL }}\";" >> lib/ota_manager/src/ota_constants.h
          echo "const String OTA_FIRMWARE_URL = \"${{ secrets.FIRMWARE_URL }}\";" >> lib/ota_manager/src/ota_constants.h
          echo "const String OTA_FIRMWARE_CHECKSUM_URL = \"${{ secrets.FIRMWARE_CHECKSUM_URL }}\";" >> lib/ota_manager/src/ota_constants.h
          echo "" >> lib/ota_manager/src/ota_constants.h
          echo "#endif // OTA_CONSTANTS_H" >> lib/ota_manager/src/ota_constants.h

      - name: Inject secrets into config.h
        run: |
          echo "#ifndef CONFIG_H" > include/config.h
          echo "#define CONFIG_H" >> include/config.h
          echo "const char *WIFI_SSID = \"$WIFI_SSID\";" >> include/config.h
          echo "const char *WIFI_PASSWORD = \"$WIFI_PASSWORD\";" >> include/config.h
          echo "const char *SERVER_KEY = \"$SERVER_KEY\";" >> include/config.h
          echo "const char *STATION_CODE = \"$STATION_CODE\";" >> include/config.h
          echo "const char *VERSION = \"${{ steps.gitversion.outputs.FullSemVer }}\";" >> include/config.h
          echo "#endif // CONFIG_H" >> include/config.h
        env:
          WIFI_SSID: ${{ secrets.WIFI_SSID }}
          WIFI_PASSWORD: ${{ secrets.WIFI_PASSWORD }}
          SERVER_KEY: ${{ secrets.SERVER_KEY }}
          STATION_CODE: ${{ secrets.STATION_CODE }}

      - name: Echo Version Number
        run: 'echo "Version: ${{ steps.gitversion.outputs.FullSemVer }}"'

      - name: Build with PlatformIO
        run: platformio run

      - name: Generate MD5 Checksum
        id: generate_md5
        run: |
          FIRMWARE_PATH=$(find .pio/build -name "firmware.bin" | head -n 1)
          if [ ! -f $FIRMWARE_PATH ]; then
            echo "Firmware binary not found!"
            exit 1
          fi
          md5sum $FIRMWARE_PATH > $FIRMWARE_PATH.md5
          echo "MD5 checksum generated for $FIRMWARE_PATH"
          echo "md5_file_path=$FIRMWARE_PATH.md5" >> $GITHUB_OUTPUT

      - name: Store MD5 Checksum
        uses: actions/upload-artifact@v4
        with:
          name: firmware-md5
          path: ${{ steps.generate_md5.outputs.md5_file_path }}
